config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'products#index'
  resources :products
  resources :orders do
    member do
      get :purchase
      get :cancel_purchase
    end
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  before_validation :generate_number, on: :create
  
  state_machine :state, initial: :pending do
    event :proceed do
      transition to: :complete
    end

    event :cancel do
      transition to: :canceled
    end
  end

  def calculate_total(qty)
    self.total = qty * self.product.price
    self.save
  end

  def generate_number(options = {})
    options[:length]  ||= 5
    options[:letters] ||= false
    options[:prefix]  ||= "SHQ"

    possible = (0..9).to_a
    possible += ('A'..'Z').to_a if options[:letters]
    self.number ||= loop do
      # Make a random number.
      random = "#{options[:prefix]}#{(0...options[:length]).map { possible.sample }.join}"
      # Use the random  number if no other order exists with it.
      if self.class.exists?(number: random)
        # If over half of all possible options are taken add another digit.
        options[:length] += 1 if self.class.count > (10**options[:length] / 2)
      else
        break random
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.calculate_total(params[:order][:qty].to_i)
    @order.product.update_quantity(params[:order][:qty].to_i)
    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    @order = Order.find(params[:id])
    if @order.proceed!
      redirect_to orders_path, notice:"Your order has been placed"
    else
      redirect_to request.referrer, alert:"Something wrong"
    end
  end

  def cancel_purchase
    @order = Order.find(params[:id])
    if @order.cancel! && @order.product.return_quantity(params[:qty].to_i)
      redirect_to orders_path, notice:"Your order has been canceled"
    else
      redirect_to request.referrer, alert:"Something wrong"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:number, :qty, :total, :user_id, :state, :product_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :qty
    = f.number_field :qty
  .field
    = f.label :total
    = f.text_field :total
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :state
    = f.text_field :state
  .actions
    = f.submit 'Save'

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
.container
  .row
    .col-md-12
      .title-section
        %h1 My Orders


  %table.table
    %thead
      %tr
        %th Number
        %th Product Name
        %th Qty
        %th Total
        %th User
        %th State
        %th
        %th
        %th

    %tbody
      - @orders.each do |order|
        %tr
          %td= order.number
          %td= link_to order.product.name, product_path(order.product.id)
          %td= order.qty
          %td= order.total
          %td= order.user_id
          %td= order.state
          - if order.state == "pending"
            %td
              = link_to 'Cancel', cancel_purchase_order_path(order.id, qty: order.qty), data: { confirm: 'Are you sure?' }, class:"btn btn-danger"
            %td= link_to 'Purchase', purchase_order_path(order.id), class:"btn btn-success"

  %br

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @order.number
%p
  %b Qty:
  = @order.qty
%p
  %b Total:
  = @order.total
%p
  %b User:
  = @order.user_id
%p
  %b State:
  = @order.state

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path