config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'products#index'
  resources :products
  resources :orders do
    member do
      get :purchase
      get :cancel_purchase
    end
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment :image, content_type: { content_type: /\Aimage\/.*\z/ }

  def update_quantity(qty)
    self.quantity = self.quantity - qty
    self.save
  end

  def return_quantity(qty)
    self.quantity = self.quantity + qty
    self.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
-# frozen_string_literal: true
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

.form-group.form-group-default
  = f.input :name, input_html: {class: "form-control"}
.form-group.form-group-default
  = f.input :price, input_html: {class: "form-control"}
.form-group.form-group-default
  = f.input :quantity, input_html: {class: "form-control"}
.form-group.form-group-default
  = f.input :image, as: :file, input_html: {class: "form-control"}
.form-actions.text-right
  = f.button :submit, class: "btn btn-success"

app/views/products/edit.html.haml
.container
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => "/"}
    %li.breadcrumb-item.active
      %a{:href => "/products"} Products
    %li.breadcrumb-item.active
      %a{:href => "/products/#{params[:id]}"}= params[:id]
    %li.breadcrumb-item.active Edit

  = simple_form_for(@product, url: product_path(@product), method: :put) do |f|
    = render 'form', f: f

app/views/products/index.html.haml
.container
  .row
    .col-md-12
      .title-section
        %h1 Listing products  
      .pull-right  
        = link_to 'New Product', new_product_path, class: "btn btn-primary"
  
  .row.products-section
    - @products.each do |product|
      .col-md-4.m-t-20
        .product-image-wrapper
          = image_tag product.image.url
        .text-center.product-detail
          %h3= link_to product.name, product_path(product)
          %h6= number_to_idr(product.price)

app/views/products/new.html.haml
.container
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{:href => "/"}
    %li.breadcrumb-item.active
      %a{:href => "/products"} Product
    %li.breadcrumb-item.active New

  = simple_form_for(@product, url: products_path, method: :post) do |f|
    = render 'form', f: f

app/views/products/show.html.haml
.container
  %p#notice= notice

  .row
    .col-md-6
      = image_tag @product.image.url, style: "width:100%;"
    .col-md-6
      %h3= @product.name
      %h6= number_to_idr(@product.price)
      %p Available Quantity: #{@product.quantity} 
      %br/
      = simple_form_for(Order.new, url: orders_path, method: :post) do |f|
        .d-flex
          .p-2
            = f.input :qty, label:"Quantity", input_html: {class: "form-control", style:"width:100%;"}
            .d-none
              = f.input :user_id, input_html: {value: current_user.id}
            .d-none
              = f.input :product_id, input_html: {value: @product.id}
          .p-2
            %br/
            = f.button :submit, class: "btn btn-success"

  .button-sec
    = link_to 'Edit Product', edit_product_path(@product), class:"btn btn-warning"
    = link_to 'Delete Product', product_path(@product), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger"
    = link_to 'Back', products_path, class:"btn btn-info"